# Generated by Django 5.1 on 2024-10-23 20:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_chatsession_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatSession',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='tittle_session',
            new_name='title',
        ),
    ]
