# Generated by Django 5.0.7 on 2024-11-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_botresponse_remove_room_messages_room_bot_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
