# Generated by Django 5.0.7 on 2024-11-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='Sala Nova', max_length=30),
        ),
    ]
