# Generated by Django 5.0.7 on 2024-11-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='user_image',
            field=models.CharField(blank=True, default='https://avatar.iran.liara.run/public', max_length=100),
        ),
    ]
