# Generated by Django 5.0.7 on 2024-11-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_usermessage_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user_image',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
