# Generated by Django 5.0.7 on 2024-11-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_usermessage_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user_image',
        ),
    ]
